# DNUM - Staging (layer de base pour les autres projets métiers)
Staging:
  target: local
  outputs:
    anais:
      type: postgres
      host: 10.89.136.17
      user: staging_admin
      password: "{{ env_var('STAGING_PASSWORD') }}"
      port: 5432
      schema: public
      dbname: staging
    local:
      type: duckdb
      path: data/staging/duckdb_database.duckdb
      schema: main

# DNUM - Layer CertDC (dépend de la base de Staging)
CertDC:
  target: local
  outputs:
    anais:
      type: postgres
      host: 10.89.136.17
      user: certelec_dc_admin
      password: "{{ env_var('CERTDC_PASSWORD') }}"
      port: 5432
      schema: public
      dbname: certelec_dc
    local:
      type: duckdb
      path: data/certdc/duckdb_database.duckdb
      schema: main
  
# DNUM - Layer InspectionControle Personnes Agées (dépend de la base de Staging)
InspectionControlePA:
  target: local
  outputs:
    anais:
      type: postgres
      host: 10.89.136.17
      user: inspection_controle_admin
      password: "{{ env_var('INSPECTION_CONTROLE_ADMIN_PA_PASSWORD') }}"
      port: 5432
      schema: public
      dbname: inspection_controle
    local:
      type: duckdb
      path: data/inspection_controle_pa/duckdb_database.duckdb
      schema: main

# DNUM - Layer InspectionControle Personnes Handicapées (dépend de la base de Staging)
InspectionControlePH:
  target: local
  outputs:
    anais:
      type: postgres
      host: 10.89.136.17
      user: inspection_controle_admin
      password: "{{ env_var('INSPECTION_CONTROLE_ADMIN_PH_PASSWORD') }}"
      port: 5432
      schema: public
      dbname: inspection_controle
    local:
      type: duckdb
      path: data/inspection_controle_ph/duckdb_database.duckdb
      schema: main

# DNUM - Layer Helios (dépend de la base de Staging)
Helios:
  target: local
  outputs:
    anais:
      type: postgres
      host: 10.89.136.17
      user: helios_admin
      password: "{{ env_var('HELIOS_PASSWORD') }}"
      port: 5432
      schema: public
      dbname: helios
    local:
      type: duckdb
      path: data/helios/duckdb_database.duckdb
      schema: main

# DNUM - Layer Matrice Personnes Agées (dépend de la base de Staging)
Matrice_PA:
  target: local
  outputs:
    anais:
      type: postgres
      host: 10.89.136.17
      user: matrice_pa_admin
      password: "{{ env_var('MATRICE_PA_PASSWORD') }}"
      port: 5432
      schema: public
      dbname: matrice_ph
    local:
      type: duckdb
      path: data/matrice_pa/duckdb_database.duckdb
      schema: main
  
# DNUM - Layer Matrice Personnes Handicapées (dépend de la base de Staging)
Matrice_PH:
  target: local
  outputs:
    anais:
      type: postgres
      host: 10.89.136.17
      user: matrice_ph_admin
      password: "{{ env_var('MATRICE_PH_PASSWORD') }}"
      port: 5432
      schema: public
      dbname: matrice_ph
    local:
      type: duckdb
      path: data/matrice_ph/duckdb_database.duckdb
      schema: main