CREATE TABLE IF NOT EXISTS tdb_ic_siicea_missions_real (
	identifiant_mission VARCHAR,
	code_theme_igas VARCHAR,
	theme_igas VARCHAR,
	type_mission VARCHAR,
	modalite_d_investigation TEXT,
	type_planification VARCHAR,
	modalite_mission VARCHAR,
	mission_conjointe_1 VARCHAR,
	mission_conjointe_2 VARCHAR,
	departement TEXT,
	commune VARCHAR,
	adresse VARCHAR,
	groupe_cibles VARCHAR,
	cible VARCHAR,
	caractere_juridique VARCHAR,
	type_cible VARCHAR,
	code_finess TEXT,
    statut_mission VARCHAR,
	date_provisoire_visite TEXT,
	date_reelle_visite TEXT,
	date_provisoire_fin_mission VARCHAR,
	date_reelle_fin_mission VARCHAR,
	cd_finess TEXT
)