version: 2

# Sources pour DuckDB
sources:
  - name: main
    tables:
      - name: sa_insern
      - name: sa_siicea_cibles
      - name: sa_siicea_missions
      - name: sa_siicea_suites
      - name: sa_sirec
      - name: sa_sivss
      - name: sa_t_finess
      - name: v_comer
      - name: v_commune
      - name: v_commune_comer
      - name: v_commune_depuis
      - name: v_departement
      - name: v_region
      - name: cert_dc_insern_2023_2024
      - name: cert_dc_insern_n2_n1
      - name: DC_det
      - name: sa_esms
      - name: sa_hubee
      - name: sa_insee_histo
      - name: sa_pmsi
      - name: sa_rpu
      - name: sa_usld

# Sources pour PostgreSQL
  - name: public
    tables:
      - name: sa_insern
      - name: sa_siicea_cibles
      - name: sa_siicea_missions
      - name: sa_siicea_suites
      - name: sa_sirec
      - name: sa_sivss
      - name: sa_t_finess
      - name: v_comer
      - name: v_commune
      - name: v_commune_comer
      - name: v_commune_depuis
      - name: v_departement
      - name: v_region
      - name: cert_dc_insern_2023_2024
      - name: cert_dc_insern_n2_n1
      - name: DC_det
      - name: sa_esms
      - name: sa_hubee
      - name: sa_insee_histo
      - name: sa_pmsi
      - name: sa_rpu
      - name: sa_usld
