CREATE TABLE IF NOT EXISTS sa_siicea_missions (
	"Column1" INTEGER,
	"Identifiant de la mission" VARCHAR(50),
	"Mission proposée par" VARCHAR(50),
	"Secteur dintervention" VARCHAR(50),
	"Code thème IGAS" VARCHAR(50),
	"Thème IGAS" VARCHAR(256),
	"Code thème régional" VARCHAR(50),
	"Thème régional" VARCHAR(256),
	"Type dorientation" VARCHAR(50),
	"Commanditaire principal" VARCHAR(50),
	"Référent thématique" VARCHAR(50),
	"Références règlementaires" VARCHAR(128),
	"Type de mission" VARCHAR(50),
	"Modalité dinvestigation" VARCHAR(50),
	"Type de planification" VARCHAR(50),
	"Modalité de la mission" VARCHAR(50),
	"Critère de ciblage 1" VARCHAR(128),
	"Critère de ciblage 2" VARCHAR(50),
	"Critère de ciblage 3" VARCHAR(50),
	"Mission conjointe avec 1" VARCHAR(50),
	"Mission conjointe avec 2" VARCHAR(50),
	"Code UAI" VARCHAR(50),
	"Code RPPS" VARCHAR(50),
	"Code SIRET" TEXT,
	"Département" TEXT,
	"Commune" VARCHAR(50),
	"Adresse" VARCHAR(50),
	"Groupe de cibles" VARCHAR(50),
	"Cible" VARCHAR(50),
	"Service ciblé " VARCHAR(256),
	"Caractère juridique" VARCHAR(50),
	"Type de cible" VARCHAR(50),
	"Code FINESS" TEXT,
	"Nom Agent 1" VARCHAR(50),
	"Prénom Agent 1" VARCHAR(50),
	"Rôle mission agent 1" VARCHAR(50),
	"Profession agent 1" VARCHAR(50),
	"Statut agent 1" VARCHAR(50),
	"Département agent 1" VARCHAR(50),
	"Temps total agent 1" INTEGER,
	"Nom Agent 2" VARCHAR(50),
	"Prénom Agent 2" VARCHAR(50),
	"Rôle mission agent 2" VARCHAR(50),
	"Profession agent 2" VARCHAR(50),
	"Statut agent 2" VARCHAR(50),
	"Département agent 2" VARCHAR(50),
	"Temps total agent 2" INTEGER,
	"Nom Agent 3" VARCHAR(50),
	"Prénom Agent 3" VARCHAR(50),
	"Rôle mission agent 3" VARCHAR(50),
	"Profession agent 3" VARCHAR(50),
	"Statut agent 3" VARCHAR(50),
	"Département agent 3" VARCHAR(50),
	"Temps total agent 3" INTEGER,
	"Nom Agent 4" VARCHAR(50),
	"Prénom Agent 4" VARCHAR(50),
	"Rôle mission agent 4" VARCHAR(50),
	"Profession agent 4" VARCHAR(50),
	"Statut agent 4" VARCHAR(50),
	"Département agent 4" VARCHAR(50),
	"Temps total agent 4" INTEGER,
	"Nom Agent 5" VARCHAR(50),
	"Prénom Agent 5" VARCHAR(50),
	"Rôle mission agent 5" VARCHAR(50),
	"Profession agent 5" VARCHAR(50),
	"Statut agent 5" VARCHAR(50),
	"Département agent 5" VARCHAR(50),
	"Temps total agent 5" INTEGER,
	"Nom Agent 6" VARCHAR(50),
	"Prénom Agent 6" VARCHAR(50),
	"Rôle mission agent 6" VARCHAR(50),
	"Profession agent 6" VARCHAR(50),
	"Statut agent 6" VARCHAR(50),
	"Département agent 6" VARCHAR(50),
	"Temps total agent 6" VARCHAR(50),
	"Nom Agent 7" VARCHAR(50),
	"Prénom Agent 7" VARCHAR(50),
	"Rôle mission agent 7" VARCHAR(50),
	"Profession agent 7" VARCHAR(50),
	"Statut agent 7" VARCHAR(50),
	"Département agent 7" VARCHAR(50),
	"Temps total agent 7" VARCHAR(50),
	"Nom Agent 8" VARCHAR(50),
	"Prénom Agent 8" VARCHAR(50),
	"Rôle mission agent 8" VARCHAR(50),
	"Profession agent 8" VARCHAR(50),
	"Statut agent 8" VARCHAR(50),
	"Département agent 8" VARCHAR(50),
	"Temps total agent 8" VARCHAR(50),
	"Nom Agent 9" VARCHAR(50),
	"Prénom Agent 9" VARCHAR(50),
	"Rôle mission agent 9" VARCHAR(50),
	"Profession agent 9" VARCHAR(50),
	"Statut agent 9" VARCHAR(50),
	"Département agent 9" VARCHAR(50),
	"Temps total agent 9" VARCHAR(50),
	"Nom Agent 10" VARCHAR(50),
	"Prénom Agent 10" VARCHAR(50),
	"Rôle mission agent 10" VARCHAR(50),
	"Profession agent 10" VARCHAR(50),
	"Statut agent 10" VARCHAR(50),
	"Département agent 10" VARCHAR(50),
	"Temps total agent 10" VARCHAR(50),
	"Commentaire" VARCHAR(50),
	"Période de réalisation" VARCHAR(50),
	"Date provisoire ""Début Mission""" VARCHAR(50),
	"Date réelle ""Début Mission""" VARCHAR(50),
	"Etat davancement ""Début Mission""" VARCHAR(50),
	"Date provisoire ""Visite""" VARCHAR(50),
	"Date réelle ""Visite""" VARCHAR(50),
	"Etat davancement ""Visite""" VARCHAR(50),
	"Date provisoire ""Rapport""" VARCHAR(50),
	"Date réelle ""Rapport""" VARCHAR(50),
	"Etat davancement ""Rapport""" VARCHAR(50),
	"Date provisoire ""Fin Mission""" VARCHAR(50),
	"Date réelle ""Fin Mission""" VARCHAR(50),
	"Etat davancement ""Fin Mission""" VARCHAR(50),
	"Commentaire.1" VARCHAR(64),
	"Niveau de risque" VARCHAR(50),
	"Nombre décarts" INTEGER,
	"Nombre de remarques" INTEGER,
	"Injonction" INTEGER,
	"Complément" VARCHAR(50),
	"Prescription" INTEGER,
	"Recommandation" INTEGER,
	"Saisine CNG" INTEGER,
	"Saisine juridiction/ordinale" INTEGER,
	"Saisine parquet" INTEGER,
	"Autre saisine" INTEGER,
	"Commentaire.2" VARCHAR(50),
	"Statut de la mission" VARCHAR(50),
	"Mission rattachement" VARCHAR(50)
)
