CREATE TABLE IF NOT EXISTS "v_commune_comer" (
	COM_COMER TEXT,
	TNCC TEXT,
	NCC VARCHAR(50),
	NCCENR VARCHAR(50),
	LIBELLE VARCHAR(50),
	NATURE_ZONAGE VARCHAR(50),
	COMER TEXT,
	LIBELLE_COMER VARCHAR(50)
)
