CREATE TABLE IF NOT EXISTS "v_commune" (
	TYPECOM TEXT,
	COM TEXT,
	REG TEXT,
	DEP TEXT,
	CTCD TEXT,
	ARR TEXT,
	TNCC TEXT,
	NCC VARCHAR(50),
	NCCENR VARCHAR(50),
	LIBELLE VARCHAR(50),
	CAN TEXT,
	COMPARENT TEXT
)
