{{ config(
    materialized='view'
) }}

SELECT
    identifiant_de_la_mission AS identifiant_mission,
    mission_proposee_par,
    secteur_d_intervention,
    code_theme_igas,
    theme_igas,
    code_theme_regional,
    theme_regional,
    type_d_orientation,
    commanditaire_principal,
    referent_thematique,
    references_reglementaires,
    type_de_mission AS type_mission,
    modalite_d_investigation,
    type_de_planification AS type_planification,
    modalite_de_la_mission AS modalite_mission,
    critere_de_ciblage_1,
    critere_de_ciblage_2,
    critere_de_ciblage_3,
    mission_conjointe_avec_1 AS mission_conjointe_1,
    mission_conjointe_avec_2 AS mission_conjointe_2,
    code_uai,
    code_rpps,
    code_siret,
    departement,
    commune,
    adresse,
    groupe_de_cibles  AS groupe_cibles,
    cible,
    service_cible,
    caractere_juridique,
    type_de_cible,
    finess_geographique AS code_finess,
    nom_agent_1,
    prenom_agent_1,
    role_mission_agent_1,
    profession_agent_1,
    statut_agent_1,
    departement_agent_1,
    temps_total_agent_1,
    nom_agent_2,
    prenom_agent_2,
    role_mission_agent_2,
    profession_agent_2,
    statut_agent_2,
    departement_agent_2,
    temps_total_agent_2,
    nom_agent_3,
    prenom_agent_3,
    role_mission_agent_3,
    profession_agent_3,
    statut_agent_3,
    departement_agent_3,
    temps_total_agent_3,
    nom_agent_4,
    prenom_agent_4,
    role_mission_agent_4,
    profession_agent_4,
    statut_agent_4,
    departement_agent_4,
    temps_total_agent_4,
    nom_agent_5,
    prenom_agent_5,
    role_mission_agent_5,
    profession_agent_5,
    statut_agent_5,
    departement_agent_5,
    temps_total_agent_5,
    nom_agent_6,
    prenom_agent_6,
    role_mission_agent_6,
    profession_agent_6,
    statut_agent_6,
    departement_agent_6,
    temps_total_agent_6,
    nom_agent_7,
    prenom_agent_7,
    role_mission_agent_7,
    profession_agent_7,
    statut_agent_7,
    departement_agent_7,
    temps_total_agent_7,
    nom_agent_8,
    prenom_agent_8,
    role_mission_agent_8,
    profession_agent_8,
    statut_agent_8,
    departement_agent_8,
    temps_total_agent_8,
    nom_agent_9,
    prenom_agent_9,
    role_mission_agent_9,
    profession_agent_9,
    statut_agent_9,
    departement_agent_9,
    temps_total_agent_9,
    nom_agent_10,
    prenom_agent_10,
    role_mission_agent_10,
    profession_agent_10,
    statut_agent_10,
    departement_agent_10,
    temps_total_agent_10,
    commentaire,
    periode_de_realisation,
    date_provisoire_debut_mission,
    date_reelle_debut_mission,
    etat_d_avancement_debut_mission,
    etat_d_avancement_visite,
    date_provisoire_rapport,
    date_reelle_rapport,
    etat_d_avancement_rapport,
    date_provisoire_fin_mission,
    date_reelle_fin_mission,
    etat_d_avancement_fin_mission,
    commentaire_1,
    niveau_de_risque,
    nombre_d_ecarts,
    nombre_de_remarques,
    injonction,
    complement,
    prescription,
    recommandation,
    saisine_cng,
    saisine_juridiction_ordinale,
    saisine_parquet,
    autre_saisine,
    commentaire_2,
    statut_de_la_mission AS statut_mission,
    CASE
        WHEN LENGTH(date_provisoire_visite) = 10 
        THEN SUBSTRING(date_provisoire_visite, 7, 4) || '-' ||
                SUBSTRING(date_provisoire_visite, 4, 2) || '-' ||
                SUBSTRING(date_provisoire_visite, 1, 2) || ' 00:00:00'
        ELSE date_provisoire_visite
    END AS date_provisoire_visite,

    CASE
        WHEN LENGTH(date_reelle_visite) = 10 
        THEN SUBSTRING(date_reelle_visite, 7, 4) || '-' ||
                SUBSTRING(date_reelle_visite, 4, 2) || '-' ||
                SUBSTRING(date_reelle_visite, 1, 2) || ' 00:00:00'
        ELSE date_reelle_visite
    END AS date_reelle_visite,
    CASE 
        WHEN LENGTH(finess_geographique) = 8 THEN '0' || finess_geographique
        ELSE finess_geographique
    END AS cd_finess
FROM {{ source(get_source_schema(), 'sa_siicea_missions_prog') }}