{{ config(
    materialized='view'
) }}

WITH sirec AS (
    SELECT * FROM {{ ref('staging__sa_sirec') }}
)

SELECT 
    numero_de_la_reclamation AS numero_reclamation,
    ancien_numero_de_la_reclamation AS ancien_numero_reclamation,
    numero_demat_social,
    service_gestionnaire,
    statut_de_la_reclamation AS statut_reclamation,
    services_en_lecture,
    signalement,
    date_de_la_demande_du_requerant AS date_demande_requerant,
    date_de_reception_a_l_ars AS date_reception_ars,
    service_de_premier_niveau AS service_premier_niveau,
    date_de_reception_au_service_de_premier_niveau AS date_reception_service_premier_niveau,
    description,
    date_de_creation_de_la_reclamation AS date_creation_reclamation,
    domaine_fonctionnel,
    mode_de_reception AS mode_reception,
    prioritaire_oui_non,
    precisions_sur_le_caractere_prioritaire AS precisions_caractere_prioritaire,
    departement_de_la_reclamation AS departement_reclamation,
    destinataire_s_de_la_reclamation AS destinataires_reclamation,
    destinataire_primaire,
    destinataire_secondaire,
    saisine_du_procureur_par_requerant AS saisine_procureur_requerant,
    institutions_de_provenance AS institutions_provenance,
    date_de_reception_a_l_institution_de_provenance AS date_reception_institution_provenance,
    reponse_attendue,
    courrier_signale_oui_non,
    le_requerant_est,
    le_requerant_est_anonyme,
    le_requerant_souhaite_garder_l_anonymat,
    statut_du_requerant AS statut_requerant,
    plus_de_2_reclamations_deposees,
    usager_victime_non_identifiee,
    sans_mis_en_cause,
    CAST(n_finess_rpps AS VARCHAR)
    autre_type,
    nom_structure,
    adresse,
    code_postal,
    ville,
    service_pour_les_etablissements_sanitaires AS service_etablissements_sanitaires,
    observations_du_mis_en_cause AS observations_mis_en_cause,
    motifs_igas_entree,
    motifs_igas_sortie,
    niveau_de_competence_de_traitement_de_la_reclamation AS niveau_competence_traitement_reclamation,
    institution_s_partenaire_s AS institutions_partenaires,
    precisions_sur_le_niveau_de_competence_de_traitement_de_la_reclamation AS precisions_niveau_competence_traitement_reclamation,
    envoi_d_un_accuse_reception AS envoi_accuse_reception,
    date_d_envoi_de_l_ar AS date_envoi_ar,
    precisions_sur_le_non_envoi_de_l_ar AS precisions_non_envoi_ar,
    date_de_transfert_a_l_institution_competente AS date_transfert_institution_competente,
    date_de_prise_en_charge_par_le_service_gestionnaire AS date_prise_en_charge_service_gestionnaire,
    type_de_traitement AS type_traitement,
    precisions_sur_le_type_de_traitement AS precisions_type_traitement,
    reclamation_en_lien_avec_un_ou_plusieurs_signalements AS reclamation_lien_signalements,
    numero_s_de_signalement_s_associe_s AS numeros_signalements_associes,
    date_d_examen_en_commission AS date_examen_commission,
    type_d_action AS type_action,
    mesures_prises_par_le_mis_en_cause AS mesures_mis_en_cause,
    mesures_a_l_initiative_de AS mesures_a_initiative,
    reponse_au_requerant_par_l_ars AS reponse_requerant_ars,
    date_de_reponse_au_requerant AS date_reponse_requerant,
    precisions_sur_la_reponse_au_requerant AS precisions_reponse_requerant,
    date_de_reponse_a_l_institution_de_provenance AS date_reponse_institution_provenance,
    motif_de_cloture AS motif_cloture,
    commentaire,
    date_de_cloture AS date_cloture,
    siege_ars,
    motifs_declares

FROM sirec
WHERE LENGTH(CAST(n_finess_rpps AS VARCHAR)) IN (8, 9)
AND date_de_reception_a_l_ars < '2024-12-31'