CREATE TABLE sa_hubee (
	type_d_organisation VARCHAR,
	companyregister_de_l_organisation TEXT,
	branchcode_de_l_organisation VARCHAR,
	nom_de_l_organisation VARCHAR,
	nom_operateur_de_service_en_ligne VARCHAR,
	code_demarche VARCHAR,
	nom_de_la_demarche VARCHAR,
	n_datapass VARCHAR,
	modalite_d_acces VARCHAR,
	statut VARCHAR,
	date_de_creation VARCHAR,
	date_de_validation VARCHAR,
	date_d_activation VARCHAR,
	date_de_suspension VARCHAR,
	date_de_modification VARCHAR,
	frequence_de_notification VARCHAR,
	email_de_notification VARCHAR,
	administrateur_local VARCHAR,
	edt VARCHAR,
	companyregister_edt VARCHAR,
	branchcode_edt VARCHAR,
	nom_de_l_organisation_edt VARCHAR
)