CREATE TABLE sa_sirec (
	"Numéro de la réclamation" TEXT(50),
	"Ancien numéro de la réclamation" TEXT(50),
	"Numéro Démat Social" VARCHAR(50),
	"Service gestionnaire" VARCHAR(50),
	"Statut de la réclamation" VARCHAR(50),
	"Services en lecture" VARCHAR(50),
	Signalement VARCHAR(50),
	"Date de la demande du requérant" VARCHAR(50),
	"Date de réception à l’ARS" VARCHAR(50),
	"Service de premier niveau" VARCHAR(50),
	"Date de réception au service de premier niveau" VARCHAR(50),
	Description VARCHAR(1024),
	"Date de création de la réclamation" VARCHAR(50),
	"Domaine fonctionnel" VARCHAR(50),
	"Mode de réception" VARCHAR(50),
	"Prioritaire : Oui/Non" VARCHAR(50),
	"Précisions sur le caractère prioritaire" VARCHAR(50),
	"Département de la réclamation" VARCHAR(50),
	"Destinataire(s) de la réclamation" VARCHAR(50),
	"Destinataire primaire" VARCHAR(128),
	"Destinataire secondaire" VARCHAR(128),
	"Saisine du procureur par requérant" VARCHAR(50),
	"Institutions de provenance" VARCHAR(50),
	"Date de réception à l'institution de provenance" VARCHAR(50),
	reponse_attendue BIGINT,
	"Courrier signalé : Oui/Non" VARCHAR(50),
	"Le requérant est" VARCHAR(50),
	"Le requérant est anonyme" VARCHAR(50),
	"Le requérant souhaite garder l'anonymat" VARCHAR(50),
	"Statut du requérant" VARCHAR(50),
	"Plus de 2 réclamations déposées" VARCHAR(50),
	"Usager (victime) non identifiée" VARCHAR(50),
	"Sans mis en cause" VARCHAR(50),
	"N° FINESS/RPPS" TEXT(50),
	Autre_Type VARCHAR(50),
	"Nom structure" VARCHAR(64),
	Adresse VARCHAR(50),
	"Code postal" BIGINT,
	Ville VARCHAR(50),
	"Service pour les établissements sanitaires" VARCHAR(50),
	"Observations du mis en cause" VARCHAR(512),
	"Motifs IGAS entrée" VARCHAR(1024),
	"Motifs IGAS sortie" VARCHAR(50),
	"Niveau de compétence de traitement de la réclamation" VARCHAR(50),
	"Institution(s) partenaire(s)" VARCHAR(50),
	"Précisions sur le niveau de compétence de traitement de la réclamation" VARCHAR(256),
	"Envoi d'un accusé réception" VARCHAR(50),
	"Date d'envoi de l'AR" VARCHAR(50),
	"Précisions sur le non envoi de l'AR" VARCHAR(128),
	"Date de transfert à l'institution compétente" VARCHAR(50),
	"Date de prise en charge par le service gestionnaire" VARCHAR(50),
	"Type de traitement" VARCHAR(50),
	"Précisions sur le type de traitement" VARCHAR(256),
	"Réclamation en lien avec un ou plusieurs signalements" VARCHAR(50),
	"Numéro(s) de signalement(s) associé(s)" VARCHAR(50),
	"Date d'examen en commission" VARCHAR(50),
	"Type d'action" VARCHAR(8192),
	"Mesures prises par le mis en cause" VARCHAR(50),
	"Mesures à l'initiative de" VARCHAR(50),
	"Réponse au requérant par l'ARS" VARCHAR(50),
	"Date de réponse au requérant" VARCHAR(50),
	"Précisions sur la réponse au requérant" VARCHAR(128),
	"Date de réponse  à l'institution de provenance" VARCHAR(50),
	"Motif de clôture" VARCHAR(64),
	Commentaire VARCHAR(256),
	"Date de clôture" VARCHAR(50),
	"Siège ARS" VARCHAR(50),
	"Motifs déclarés" VARCHAR(128)
)
