CREATE TABLE "v_commune" (
	TYPECOM TEXT(50),
	COM TEXT(50),
	REG TEXT(50),
	DEP TEXT(50),
	CTCD TEXT(50),
	ARR TEXT(50),
	TNCC TEXT(50),
	NCC VARCHAR(50),
	NCCENR VARCHAR(50),
	LIBELLE VARCHAR(50),
	CAN TEXT(50),
	COMPARENT TEXT(50)
)
