CREATE TABLE "v_commune_comer" (
	COM_COMER TEXT(50),
	TNCC TEXT(50),
	NCC VARCHAR(50),
	NCCENR VARCHAR(50),
	LIBELLE VARCHAR(50),
	NATURE_ZONAGE VARCHAR(50),
	COMER TEXT(50),
	LIBELLE_COMER VARCHAR(50)
)
